version: '3.8'

services:
  db-vivero:
    image: postgres:15
    container_name: postgres-vivero
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  api-vivero:
    build: .
    container_name: spring-vivero
    ports:
      - "${APP_PORT}:8080"
    environment:
      # Pasamos las variables al application.properties de Spring
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-vivero:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db-vivero
    restart: always
