logging.level.org.springframework.security=DEBUG
server.error.include-message=always
spring.mvc.log-resolved-exception=true

# Quita la URL hardcodeada, deja que venga del entorno
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}