logging.level.org.springframework.security=DEBUG
server.error.include-message=always
spring.mvc.log-resolved-exception=true
spring.datasource.url=jdbc:postgresql://localhost:5432/vivero_db
spring.datasource.username=user_vivero
spring.datasource.password=password_vivero
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
